//! Reads `integration-tests/versions.toml` and generates a `FIXTURE_VERSIONS`
//! const into `$OUT_DIR/fixture_versions.rs`. The integration tests
//! `include!` this file via `tests/common/versions.rs`.
//!
//! This script runs once per `cargo build` / `cargo test` of the nifi-lens
//! package. It intentionally lives at the package root (not `tests/`) because
//! Cargo only runs one `build.rs` per package.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let versions_toml = manifest_dir.join("integration-tests").join("versions.toml");
    println!("cargo:rerun-if-changed={}", versions_toml.display());

    let toml_str = fs::read_to_string(&versions_toml)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", versions_toml.display()));

    let parsed: toml::Value = toml::from_str(&toml_str)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", versions_toml.display()));

    let versions: Vec<String> = parsed["versions"]
        .as_array()
        .expect("versions must be a TOML array")
        .iter()
        .map(|v| {
            v.as_str()
                .expect("each version must be a string")
                .to_string()
        })
        .collect();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = PathBuf::from(out_dir).join("fixture_versions.rs");
    let quoted: Vec<String> = versions.iter().map(|v| format!("\"{v}\"")).collect();
    let generated = format!(
        "// Auto-generated by build.rs from integration-tests/versions.toml.\n\
         // Do not edit by hand.\n\
         pub const FIXTURE_VERSIONS: &[&str] = &[{}];\n",
        quoted.join(", ")
    );
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
