//! Reads `integration-tests/versions.toml` and generates a `FIXTURE_VERSIONS`
//! const into `$OUT_DIR/fixture_versions.rs`. The integration tests
//! `include!` this file via `tests/common/versions.rs`.
//!
//! This script runs once per `cargo build` / `cargo test` of the nifi-lens
//! package. It intentionally lives at the package root (not `tests/`) because
//! Cargo only runs one `build.rs` per package.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    // Emit the nifi-rust-client version from Cargo.lock so src/lib.rs can
    // print it in the version command without a hardcoded string.
    let cargo_lock = manifest_dir.join("Cargo.lock");
    println!("cargo:rerun-if-changed={}", cargo_lock.display());
    let lock_str = fs::read_to_string(&cargo_lock)
        .unwrap_or_else(|e| panic!("failed to read Cargo.lock: {e}"));
    let lock: toml::Value =
        toml::from_str(&lock_str).unwrap_or_else(|e| panic!("failed to parse Cargo.lock: {e}"));
    let nifi_version = lock["package"]
        .as_array()
        .expect("Cargo.lock must have [[package]] entries")
        .iter()
        .find(|pkg| pkg["name"].as_str() == Some("nifi-rust-client"))
        .and_then(|pkg| pkg["version"].as_str())
        .expect("nifi-rust-client not found in Cargo.lock");
    println!("cargo:rustc-env=NIFI_RUST_CLIENT_VERSION={nifi_version}");

    let versions_toml = manifest_dir.join("integration-tests").join("versions.toml");
    println!("cargo:rerun-if-changed={}", versions_toml.display());

    let toml_str = fs::read_to_string(&versions_toml)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", versions_toml.display()));

    let parsed: toml::Value = toml::from_str(&toml_str)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", versions_toml.display()));

    let versions: Vec<String> = parsed["versions"]
        .as_array()
        .expect("versions must be a TOML array")
        .iter()
        .map(|v| {
            v.as_str()
                .expect("each version must be a string")
                .to_string()
        })
        .collect();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = PathBuf::from(out_dir).join("fixture_versions.rs");
    let quoted: Vec<String> = versions.iter().map(|v| format!("\"{v}\"")).collect();
    let generated = format!(
        "// Auto-generated by build.rs from integration-tests/versions.toml.\n\
         // Do not edit by hand.\n\
         pub const FIXTURE_VERSIONS: &[&str] = &[{}];\n",
        quoted.join(", ")
    );
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
