//! Generate the orders_payload.csv asset for the integration test fixture.
//!
//! Reproducible: uses a fixed RNG seed (42) so the same git checkout always
//! produces byte-identical output. Run from the workspace root:
//!
//! ```bash
//! cargo run -p gen-orders-payload \
//!     > integration-tests/seeder/assets/orders_payload.csv
//! ```

use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use std::fmt::Write as _;

const RECORD_COUNT: usize = 10_000;
const RNG_SEED: u64 = 42;

const KIB: usize = 1024;
const MIB: usize = 1024 * KIB;

const REGIONS: &[(&str, &str)] = &[("EU", "EUR"), ("US", "USD"), ("APAC", "SGD")];

const STATUSES: &[&str] = &["PENDING", "CONFIRMED", "SHIPPED", "CANCELLED"];

fn main() {
    let mut rng = ChaCha8Rng::seed_from_u64(RNG_SEED);
    let mut out = String::with_capacity(MIB);
    out.push_str("# generated by seeder/tools/gen-orders-payload (seed=42)\n");
    out.push_str("order_id,customer_id,region,sku,qty,unit_price_local,currency,subtotal_local,status,created_at\n");

    for i in 1..=RECORD_COUNT {
        let region_idx = i % REGIONS.len();
        let (region, currency) = REGIONS[region_idx];
        let qty: u32 = rng.gen_range(1..=5);
        let price_cents: u32 = rng.gen_range(500..=9999);
        let unit_price = price_cents as f64 / 100.0;
        let subtotal = unit_price * qty as f64;
        let sku_letter = (b'A' + rng.gen_range(0..26)) as char;
        let sku_num: u32 = rng.gen_range(0..1000);
        let cust: u32 = rng.gen_range(0..100_000);
        let status = STATUSES[rng.gen_range(0..STATUSES.len())];
        // Spread over ~14 days ending 2026-04-28.
        let day_offset: u32 = rng.gen_range(0..14);
        let day = 28 - day_offset;
        let hour: u32 = rng.gen_range(0..24);
        let minute: u32 = rng.gen_range(0..60);
        let second: u32 = rng.gen_range(0..60);

        write!(
            &mut out,
            "ORD-{:07},CUST-{:05},{},SKU-{}{:03},{},{:.2},{},{:.2},{},2026-04-{:02}T{:02}:{:02}:{:02}Z\n",
            i,
            cust,
            region,
            sku_letter,
            sku_num,
            qty,
            unit_price,
            currency,
            subtotal,
            status,
            day,
            hour,
            minute,
            second,
        ).unwrap();
    }

    print!("{out}");
}
