//! Remote-pipeline fixture: a top-level PG containing two Remote Process
//! Groups (RPGs) for live coverage of nifi-lens's RPG read paths.
//!
//! ```text
//! remote-pipeline/
//! ├── transmitting-rpg   (run_status: TRANSMITTING, target = floor NiFi)
//! └── idle-rpg           (run_status: STOPPED — default after create)
//! ```
//!
//! Both RPGs target the floor NiFi's own bind URL
//! (`https://nifi-2-6-0:8443/nifi`). That hostname is resolvable across
//! containers in the integration-tests docker network. The floor NiFi's
//! TLS cert (generated by `integration-tests/scripts/generate-certs.sh`)
//! lists `nifi-2-6-0` in its SANs and site-to-site listening is enabled
//! via `nifi.remote.input.*` properties, so the SSL handshake succeeds
//! and the RPG can transition to TRANSMITTING and accumulate status
//! history buckets.
//!
//! Used by `tests/integration_remote_process_groups.rs` (Task 21).

use nifi_rust_client::dynamic::{DynamicClient, types};

use crate::error::{Result, SeederError};
use crate::fixture::common::create_child_pg;

/// Hostname:port of the floor NiFi inside the docker compose network.
/// Resolvable from the cluster nodes too (shared docker network). The
/// floor NiFi binds HTTPS on 8443 — see `integration-tests/docker-compose.yml`.
const REMOTE_TARGET_URI: &str = "https://nifi-2-6-0:8443/nifi";

/// Create the `remote-pipeline` PG under `parent_pg_id` with two RPGs:
/// `transmitting-rpg` (started → TRANSMITTING) and `idle-rpg` (STOPPED).
pub async fn seed(client: &DynamicClient, parent_pg_id: &str) -> Result<()> {
    tracing::info!("seeding remote-pipeline");

    let pg_id = create_child_pg(client, parent_pg_id, "remote-pipeline").await?;

    let transmitting_id =
        create_remote_process_group(client, &pg_id, "transmitting-rpg", REMOTE_TARGET_URI).await?;
    set_rpg_run_status(
        client,
        &transmitting_id,
        types::RemotePortRunStatusEntityState::Transmitting,
    )
    .await?;
    tracing::info!(%transmitting_id, "transmitting-rpg created and set TRANSMITTING");

    let idle_id =
        create_remote_process_group(client, &pg_id, "idle-rpg", REMOTE_TARGET_URI).await?;
    tracing::info!(%idle_id, "idle-rpg created (default STOPPED)");

    tracing::info!("remote-pipeline seeded");
    Ok(())
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// POST a new Remote Process Group under `pg_id` with the given target URI.
async fn create_remote_process_group(
    client: &DynamicClient,
    pg_id: &str,
    name: &str,
    target_uri: &str,
) -> Result<String> {
    let body = make_rpg_entity(name, target_uri);
    let created = client
        .processgroups()
        .create_remote_process_group(pg_id, &body)
        .await
        .map_err(|e| SeederError::Api {
            message: format!("create remote process group {name}"),
            source: Box::new(e),
        })?;
    created
        .component
        .and_then(|c| c.id)
        .or(created.id)
        .ok_or_else(|| SeederError::Invariant {
            message: format!("remote process group {name} has no id after create"),
        })
}

/// Build a `RemoteProcessGroupEntity` for creation. Uses the singular
/// `target_uri` field (supported on every NiFi 2.x version including the
/// 2.6.0 floor), and lets NiFi default the rest of the DTO.
fn make_rpg_entity(name: &str, target_uri: &str) -> types::RemoteProcessGroupEntity {
    let mut component = types::RemoteProcessGroupDto::default();
    component.name = Some(name.to_string());
    component.target_uri = Some(target_uri.to_string());

    let mut revision = types::RevisionDto::default();
    revision.version = Some(0);

    let mut entity = types::RemoteProcessGroupEntity::default();
    entity.component = Some(component);
    entity.revision = Some(revision);
    entity
}

/// Build a `RemotePortRunStatusEntity` requesting `state` at the given
/// `revision_version`. The body needs the current revision — NiFi enforces
/// optimistic concurrency on `/run-status` PUTs. The caller is responsible
/// for supplying a fresh version obtained immediately before the PUT.
///
/// The dynamic `state` field is `Option<String>`; we serialise the typed
/// helper enum via its `as_str()` wire form so the conversion lives in
/// one place.
fn make_run_status(
    revision_version: i64,
    state: types::RemotePortRunStatusEntityState,
) -> types::RemotePortRunStatusEntity {
    let mut revision = types::RevisionDto::default();
    revision.version = Some(revision_version);

    let mut entity = types::RemotePortRunStatusEntity::default();
    entity.revision = Some(revision);
    entity.state = Some(state.as_str().to_string());
    entity
}

/// PUT `/remote-process-groups/{id}/run-status` to transition the RPG.
///
/// Fetches the current revision immediately before the PUT — NiFi may have
/// advanced the version counter during the target-side handshake that occurs
/// after `create_remote_process_group` returns, so hardcoding revision 0
/// causes a 400 "not the most up-to-date revision" error on live clusters.
async fn set_rpg_run_status(
    client: &DynamicClient,
    rpg_id: &str,
    state: types::RemotePortRunStatusEntityState,
) -> Result<()> {
    let entity = client
        .remoteprocessgroups()
        .get_remote_process_group(rpg_id)
        .await
        .map_err(|e| SeederError::Api {
            message: format!("get remote process group {rpg_id} for revision"),
            source: Box::new(e),
        })?;
    let revision_version = entity
        .revision
        .as_ref()
        .and_then(|r| r.version)
        .unwrap_or(0);
    let body = make_run_status(revision_version, state);
    client
        .remoteprocessgroups()
        .update_remote_process_group_run_status(rpg_id, &body)
        .await
        .map_err(|e| SeederError::Api {
            message: format!("update run-status of remote process group {rpg_id}"),
            source: Box::new(e),
        })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn make_rpg_entity_sets_name_and_target_uri() {
        let entity = make_rpg_entity("transmitting-rpg", "https://nifi-east:8443/nifi");
        let component = entity.component.unwrap();
        assert_eq!(component.name.as_deref(), Some("transmitting-rpg"));
        assert_eq!(
            component.target_uri.as_deref(),
            Some("https://nifi-east:8443/nifi")
        );
        let rev = entity.revision.unwrap();
        assert_eq!(rev.version, Some(0));
    }

    #[test]
    fn make_run_status_sets_state_and_revision() {
        let body = make_run_status(3, types::RemotePortRunStatusEntityState::Transmitting);
        assert_eq!(body.state.as_deref(), Some("TRANSMITTING"));
        assert_eq!(body.revision.unwrap().version, Some(3));
    }

    #[test]
    fn make_run_status_serialises_stopped_as_wire_value() {
        let body = make_run_status(0, types::RemotePortRunStatusEntityState::Stopped);
        assert_eq!(body.state.as_deref(), Some("STOPPED"));
    }

    #[test]
    fn target_uri_constant_uses_floor_hostname() {
        assert!(REMOTE_TARGET_URI.contains("nifi-2-6-0"));
        assert!(REMOTE_TARGET_URI.starts_with("https://"));
    }
}
